### ISSUE TITLE
这个怎么运行  怎么验证测试

### ISSUE THREAD

**Issue by DaJiang666** [leeowenowen/AndroidUnitTest#1]
如题

**Comment by leeowenowen** [comment]
直接执行单元测试就行了

**Comment by eastcool** [comment]
求解：导入后运行RobolectricTest 这个报了如下异常，
android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f040017

	at org.robolectric.shadows.ShadowResources.checkResName(ShadowResources.java:343)
	at org.robolectric.shadows.ShadowResources.resolveResName(ShadowResources.java:338)
	at org.robolectric.shadows.ShadowResources.loadXmlResourceParser(ShadowResources.java:429)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java)
	at android.content.res.Resources.getLayout(Resources.java:1049)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:412)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
	at android.app.Activity.setContentView(Activity.java:2144)
	at owo.com.androidunittest.MainActivity.onCreate(MainActivity.java:15)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:46)
	at owo.com.androidunittest.tests.robolectric.RobolectricTest.testCreateView(RobolectricTest.java:42)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

**Comment by rayworks** [comment]
@eastcool 
AS中运行遇到同样的错误。
[设置工作目录后 test pass](https://stackoverflow.com/questions/30913522/robolectric-says-androidmanifest-xml-not-found).

**Comment by leeowenowen** [comment]
代码clone下来之后，执行./gradlew test或者./gradlew check就可以了
由于代码很久没更改了，有些依赖库已经更改，导致几个单元测试跑不过，我已经删除了。
现在已经可以跑过了
